apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zookeeper
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: zk.sihai.com
    http:
      paths:
      - path:
        backend:
          serviceName: ykszktest-n3
          servicePort: 2181
