apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: test
  labels:
    app: login
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
      
  template:
    metadata:
      labels:
        app: login
        
    spec:
      containers:
      - name: login
        image: dockerhub.sihai.com:8081/test/login:20190926093812
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harbor       

---
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: test
spec:
  selector:
    app: login
  ports:
  - port: 8080
    name: login
  type: ClusterIP
