kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: test
data:
  nginx.conf: |
    user  www-data;
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume!
        root /var/www/html/api/public;
        server_name _;

        index index.php;

        location / {
          include  /etc/nginx/mime.types;
          try_files $uri /index.php?$query_string;
        }

        location = /favicon.ico { log_not_found off; access_log off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        sendfile off;

        client_max_body_size 100m;

        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
