apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: test
  labels:
    k8s-app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: jenkins
  template:
    metadata:
      labels:
        k8s-app: jenkins
    spec:
      containers:
      - name: jenkins
        image: dockerhub.sihai.com:8081/test/web-mobile:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080 
          name: web
        - containerPort: 50000
          name: agent
      volumes:
        - name: jenkins-home
          emptyDir: {}
      imagePullSecrets:
      - name: harbor
