kind: ConfigMap
apiVersion: v1
metadata:
  name: ocelot-ocelot
  namespace: test
data:
  ocelot.json: |
    {
      "ReRoutes": [
        {
          "DownstreamPathTemplate": "/v2/api-docs",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "localhost",
              "Port": 8080
            }
          ],
          "UpstreamPathTemplate": "/sihaiapi",
          "UpstreamHttpMethod": [ "Get" ]
        }
      ]
    }
